services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
    environment:
      - ./s3.env
    volumes:
      - "./test_bucket:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"